version: '3.8'

services:
  preflight:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: preflight
    container_name: ${ORG:-default_org}_preflight
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    runtime: nvidia  # Ensure nvidia runtime is available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["/app/preflight", "check-gpu"]  # Assuming your binary has a check-gpu command
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  resource-provider:
    image: ghcr.io/lilypad-tech/resource-provider:latest
    container_name: ${ORG:-default_org}_resource-provider
    runtime: nvidia
    depends_on:
      preflight:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OFFER_GPU=1s