// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.2
// source: gpu_tools.proto

package gpu_tools_protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	RpId          string                 `protobuf:"bytes,2,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_gpu_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *InitRequest) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_gpu_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateJwtTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJwtTokenRequest) Reset() {
	*x = UpdateJwtTokenRequest{}
	mi := &file_gpu_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJwtTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJwtTokenRequest) ProtoMessage() {}

func (x *UpdateJwtTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJwtTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdateJwtTokenRequest) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateJwtTokenRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type UpdateJwtTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJwtTokenResponse) Reset() {
	*x = UpdateJwtTokenResponse{}
	mi := &file_gpu_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJwtTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJwtTokenResponse) ProtoMessage() {}

func (x *UpdateJwtTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJwtTokenResponse.ProtoReflect.Descriptor instead.
func (*UpdateJwtTokenResponse) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateJwtTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartProfilingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProfilingRequest) Reset() {
	*x = StartProfilingRequest{}
	mi := &file_gpu_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProfilingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProfilingRequest) ProtoMessage() {}

func (x *StartProfilingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProfilingRequest.ProtoReflect.Descriptor instead.
func (*StartProfilingRequest) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{4}
}

func (x *StartProfilingRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

type StartProfilingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProfilingResponse) Reset() {
	*x = StartProfilingResponse{}
	mi := &file_gpu_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProfilingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProfilingResponse) ProtoMessage() {}

func (x *StartProfilingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProfilingResponse.ProtoReflect.Descriptor instead.
func (*StartProfilingResponse) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{5}
}

func (x *StartProfilingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopProfilingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProfilingRequest) Reset() {
	*x = StopProfilingRequest{}
	mi := &file_gpu_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProfilingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProfilingRequest) ProtoMessage() {}

func (x *StopProfilingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProfilingRequest.ProtoReflect.Descriptor instead.
func (*StopProfilingRequest) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{6}
}

func (x *StopProfilingRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

type StopProfilingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProfilingResponse) Reset() {
	*x = StopProfilingResponse{}
	mi := &file_gpu_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProfilingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProfilingResponse) ProtoMessage() {}

func (x *StopProfilingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProfilingResponse.ProtoReflect.Descriptor instead.
func (*StopProfilingResponse) Descriptor() ([]byte, []int) {
	return file_gpu_tools_proto_rawDescGZIP(), []int{7}
}

func (x *StopProfilingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gpu_tools_proto protoreflect.FileDescriptor

var file_gpu_tools_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x3f, 0x0a, 0x0b,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a,
	0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x72, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x49, 0x64, 0x22, 0x28, 0x0a,
	0x0c, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x34, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x32, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x30, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x61,
	0x6c, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2f, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x64, 0x65, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x70,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xc5, 0x02, 0x0a, 0x08,
	0x47, 0x70, 0x75, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x37, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74,
	0x12, 0x16, 0x2e, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x70, 0x75, 0x5f, 0x74,
	0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x55, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x20, 0x2e, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c,
	0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x67, 0x70, 0x75,
	0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67,
	0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x52, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67,
	0x12, 0x1f, 0x2e, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x53, 0x74, 0x6f,
	0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x53, 0x74,
	0x6f, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x69, 0x6c, 0x79, 0x70, 0x61, 0x64, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x6c,
	0x69, 0x6c, 0x79, 0x70, 0x61, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x70, 0x75, 0x2d,
	0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_gpu_tools_proto_rawDescOnce sync.Once
	file_gpu_tools_proto_rawDescData []byte
)

func file_gpu_tools_proto_rawDescGZIP() []byte {
	file_gpu_tools_proto_rawDescOnce.Do(func() {
		file_gpu_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gpu_tools_proto_rawDesc), len(file_gpu_tools_proto_rawDesc)))
	})
	return file_gpu_tools_proto_rawDescData
}

var file_gpu_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gpu_tools_proto_goTypes = []any{
	(*InitRequest)(nil),            // 0: gpu_tools.InitRequest
	(*InitResponse)(nil),           // 1: gpu_tools.InitResponse
	(*UpdateJwtTokenRequest)(nil),  // 2: gpu_tools.UpdateJwtTokenRequest
	(*UpdateJwtTokenResponse)(nil), // 3: gpu_tools.UpdateJwtTokenResponse
	(*StartProfilingRequest)(nil),  // 4: gpu_tools.StartProfilingRequest
	(*StartProfilingResponse)(nil), // 5: gpu_tools.StartProfilingResponse
	(*StopProfilingRequest)(nil),   // 6: gpu_tools.StopProfilingRequest
	(*StopProfilingResponse)(nil),  // 7: gpu_tools.StopProfilingResponse
}
var file_gpu_tools_proto_depIdxs = []int32{
	0, // 0: gpu_tools.GpuTools.Init:input_type -> gpu_tools.InitRequest
	2, // 1: gpu_tools.GpuTools.UpdateJwtToken:input_type -> gpu_tools.UpdateJwtTokenRequest
	4, // 2: gpu_tools.GpuTools.StartProfiling:input_type -> gpu_tools.StartProfilingRequest
	6, // 3: gpu_tools.GpuTools.StopProfiling:input_type -> gpu_tools.StopProfilingRequest
	1, // 4: gpu_tools.GpuTools.Init:output_type -> gpu_tools.InitResponse
	3, // 5: gpu_tools.GpuTools.UpdateJwtToken:output_type -> gpu_tools.UpdateJwtTokenResponse
	5, // 6: gpu_tools.GpuTools.StartProfiling:output_type -> gpu_tools.StartProfilingResponse
	7, // 7: gpu_tools.GpuTools.StopProfiling:output_type -> gpu_tools.StopProfilingResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gpu_tools_proto_init() }
func file_gpu_tools_proto_init() {
	if File_gpu_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gpu_tools_proto_rawDesc), len(file_gpu_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpu_tools_proto_goTypes,
		DependencyIndexes: file_gpu_tools_proto_depIdxs,
		MessageInfos:      file_gpu_tools_proto_msgTypes,
	}.Build()
	File_gpu_tools_proto = out.File
	file_gpu_tools_proto_goTypes = nil
	file_gpu_tools_proto_depIdxs = nil
}
