version: '3.8'

name: lilypad-chain

services:
  lilypad-node:
    build:
      context: infra/ava
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null
    ports:
      - "9650:9650"
      - "9652:9652"
      - "9654:9654"
      - "9656:9656"
      - "9658:9658"