name: lilypad
include:
  - docker-compose.base.yml
services:
  solver:
    image: ghcr.io/lilypad-tech/solver
    container_name: solver
    depends_on:
      - chain
    build:
      context: ..
      dockerfile: ./docker/solver/Dockerfile
      args:
        - network=dev
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - WEB3_PRIVATE_KEY=${SOLVER_PRIVATE_KEY}
      - LOG_LEVEL=debug
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - WEB3_RPC_URL=${WEB3_RPC_URL}
      - DISABLE_TELEMETRY=${DISABLE_TELEMETRY}
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/job_offers"]
      interval: 30s
      timeout: 10s
      retries: 5
  job-creator:
    image: ghcr.io/lilypad-tech/job-creator
    container_name: job-creator
    restart: unless-stopped
    depends_on:
      - chain
      - solver
    build:
      context: ..
      dockerfile: ./docker/job-creator/Dockerfile
      args:
        - network=dev
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - WEB3_PRIVATE_KEY=${JOB_CREATOR_PRIVATE_KEY}
      - LOG_LEVEL=debug
  resource-provider:
    image: ghcr.io/lilypad-tech/resource-provider
    container_name: resource-provider
    restart: unless-stopped
    depends_on:
      solver:
        condition: service_healthy
      bacalhau:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/resource-provider/Dockerfile
      args:
        - NETWORK=dev
        - COMPUTE_MODE=cpu
        - VERSION=${VERSION}
        - COMMIT_SHA=${COMMIT_SHA}
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - lilypad-data:/tmp/lilypad/data
      - ${HOME}/.bacalhau:/root/.bacalhau
    environment:
      - WEB3_PRIVATE_KEY=${RESOURCE_PROVIDER_PRIVATE_KEY}
      - IPFS_CONNECT=/dns4/ipfs/tcp/5001
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=${DISABLE_TELEMETRY}
      - BACALHAU_API_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_PORT=1234
volumes:
  lilypad-data:
