# This is a docker-compose file for use by Resource Providers
services:
  bacalhau:
    image: ghcr.io/lilypad-tech/bacalhau:latest
    container_name: bacalhau
    restart: unless-stopped
    privileged: true
    build:
      context: ..
      dockerfile: ./docker/bacalhau/Dockerfile
    environment:
      - BACALHAU_ENVIRONMENT=local
    command: ["bacalhau", "serve", "--orchestrator", "--compute"]
    volumes:
      - bacalhau-data:/root/.bacalhau
  resource-provider:
    image: ghcr.io/lilypad-tech/resource-provider:latest
    container_name: resource-provider
    restart: unless-stopped
    depends_on:
      bacalhau:
        condition: service_healthy
      gpu-tools:
        condition: service_started  
    build:
      context: ..
      dockerfile: ./docker/resource-provider/Dockerfile
      args:
        - COMPUTE_MODE=gpu
    volumes:
      - lilypad-data:/tmp/lilypad/data
      - bacalhau-data:/root/.bacalhau
    environment:
      - WEB3_PRIVATE_KEY
      - WEB3_RPC_URL
      - BACALHAU_API_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_PORT=1234
      - GPU_TOOLS_HOST=gpu-tools
      - GPU_TOOLS_PORT=50051
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gpu-tools:
    image: ghcr.io/lilypad-tech/gpu-tools:latest
    container_name: gpu-tools
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/gpu-tools/Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - KAFKA_BROKER=broker
      - KAFKA_BROKER_PORT=9094
    ports:
      - "50051:50051"
    privileged: true
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu,compute,utility]
volumes:
  bacalhau-data:
  lilypad-data:
