# This is a docker-compose file for use by Resource Providers
services:
  bacalhau:
    image: ghcr.io/lilypad-tech/bacalhau:latest
    container_name: bacalhau
    ports:
      - "8438:8438"
    command: ["bacalhau", "serve", "--orchestrator", "--compute", "--config", "WebUI.Enabled"]
    runtime: nvidia
    restart: unless-stopped
    privileged: true
    build:
      context: ..
      dockerfile: ./docker/bacalhau/Dockerfile
    environment:
      - BACALHAU_ENVIRONMENT=local
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - bacalhau-data:/root/.bacalhau
  resource-provider:
    image: ghcr.io/lilypad-tech/resource-provider:latest
    container_name: resource-provider
    runtime: nvidia
    restart: unless-stopped
    depends_on:
      bacalhau:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/resource-provider/Dockerfile
      args:
        - COMPUTE_MODE=gpu
    volumes:
      - lilypad-data:/tmp/lilypad/data
      - bacalhau-data:/root/.bacalhau
    environment:
      - WEB3_PRIVATE_KEY
      - NVIDIA_VISIBLE_DEVICES=all
      - WEB3_RPC_URL
      - BACALHAU_API_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_PORT=1234
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  bacalhau-data:
  lilypad-data:
