# This is a docker-compose file for use by Resource Providers
services:
  bacalhau:
    image: ghcr.io/lilypad-tech/bacalhau:latest
    container_name: bacalhau
    restart: unless-stopped
    privileged: true
    build:
      context: ..
      dockerfile: ./docker/bacalhau/Dockerfile
    environment:
      - BACALHAU_ENVIRONMENT=local
    command: |-
      bacalhau serve --orchestrator --compute --config Compute.AllowListedLocalPaths="/inputs/*:rw"
    volumes:
      - bacalhau-data:/root/.bacalhau
      - /tmp/lilypad/data/job-inputs/:/inputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  resource-provider:
    image: ghcr.io/lilypad-tech/resource-provider:latest
    container_name: resource-provider
    restart: unless-stopped
    depends_on:
      bacalhau:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build:
      context: ..
      dockerfile: ./docker/resource-provider/Dockerfile
      args:
        - COMPUTE_MODE=gpu
    volumes:
      - lilypad-data:/tmp/lilypad/data
      - bacalhau-data:/root/.bacalhau
    environment:
      - WEB3_PRIVATE_KEY
      - WEB3_RPC_URL
      - BACALHAU_API_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_PORT=1234
      - ANURA_BASE_URL=${ANURA_BASE_URL}
      - ANURA_API_KEY=${ANURA_API_KEY}
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  bacalhau-data:
  lilypad-data:
