# This is a docker-compose file for use by Resource Providers
services:
  ipfs:
    image: ipfs/kubo:v0.32.1
    container_name: ipfs
    restart: unless-stopped
    ports:
      - 4001:4001
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
    volumes:
      - ipfs-data:/data/ipfs
  bacalhau:
    image: ghcr.io/lilypad-tech/bacalhau
    container_name: bacalhau
    restart: unless-stopped
    depends_on:
      ipfs:
        condition: service_healthy
    environment:
      - BACALHAU_ENVIRONMENT=local
    command:
      [
        "serve",
        "--node-type",
        "compute,requester",
        "--peer",
        "none",
        "--private-internal-ipfs=false",
        "--job-selection-accept-networked",
        "--ipfs-connect",
        "/dns4/ipfs/tcp/5001",
      ]
    volumes:
      - bacalhau-data:/root/.bacalhau
      - /var/run/docker.sock:/var/run/docker.sock
  resource-provider:
    image: ghcr.io/lilypad-tech/resource-provider:latest
    container_name: resource-provider
    restart: unless-stopped
    depends_on:
      - ipfs
    build:
      context: ..
      dockerfile: ./docker/resource-provider/Dockerfile
      args:
        - COMPUTE_MODE=gpu
    volumes:
      - lilypad-data:/tmp/lilypad/data
    environment:
      - WEB3_PRIVATE_KEY
      - WEB3_RPC_URL
      - IPFS_CONNECT=/dns4/ipfs/tcp/5001
      - BACALHAU_API_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_HOST=bacalhau
      - BACALHAU_NODE_CLIENTAPI_PORT=1234
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  ipfs-data:
  bacalhau-data:
  lilypad-data:
