name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install golang
        uses: actions/setup-go@v5

      - name: Install node
        uses: actions/setup-node@v4

      - name: Build Docker Images
        run: docker compose -f docker/docker-compose.dev.yml build

      - name: Initialize chain
        env:
          ADMIN_ADDRESS: ${{ secrets.INTEGRATION_TEST_ADMIN_ADDRESS }}
        run: |
          ./stack chain-clean
          docker compose -f ./docker/docker-compose.dev.yml up chain -d
          ./stack chain-boot

      - name: Run stack
        env:
          ADMIN_ADDRESS: ${{ secrets.INTEGRATION_TEST_ADMIN_ADDRESS }}
          DOPPLER_TOKEN_JOB_CREATOR: ${{ secrets.INTEGRATION_TEST_DOPPLER_TOKEN_JOB_CREATOR }}
          DOPPLER_TOKEN_SOLVER: ${{ secrets.INTEGRATION_TEST_DOPPLER_TOKEN_SOLVER }}
          WEB3_PRIVATE_KEY: ${{ secrets.INTEGRATION_TEST_WEB3_PRIVATE_KEY }}
          DISABLE_TELEMETRY: true
        run: docker compose -f ./docker/docker-compose.dev.yml up -d

      - name: Run tests
        env:
          DOPPLER_TOKEN: ${{ secrets.INTEGRATION_TESTS_DOPPLER_TOKEN }}
          LOG_LEVEL: debug
        run: ./stack integration-tests

      - name: Display resource provider logs
        run: docker logs resource-provider

      - name: Display solver logs
        run: docker logs solver

      - name: Display chain logs
        run: docker logs chain
