name: Test

on:
  push:
    branches:
      - main

    tags:

  pull_request:
    branches:
      - main

  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WEB3_PUBLIC_KEY: '0x5fbb58c8b15E498442b72E2c8Dad82266ea7e135'
  SERVICE_SOLVER: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
  SERVICE_MEDIATORS: "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
  WEB3_PRIVATE_KEY: 'beb00ab9be22a34a9c940c27d1d6bfe59db9ab9de4930c968b16724907591b3f'

#  TODO: migrate to ${{secrets.SOLVER_PRIVATE_KEY}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        check-latest: true
        cache-dependency-path: go.sum
        cache: true
        go-version-file: go.mod

    - name: Install dependencies
      run: go get .

    - name: Set Node.js
      continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        check-latest: true
        cache: 'yarn'
        cache-dependency-path: 'hardhat/yarn.lock'


    - name: Yarn
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: hardhat

#    - name: Load .env file
#      uses: xom9ikk/dotenv@v2
#      with:
#        path: './' FIXME: not working need to investigate

    - name: Source .env
      run: |
        source .env

    - name: Test Short
      run: go test -v -run="^Test" -short ./... -timeout 20m

    - name: Test
      run: go test -v -run="^Test" ./... -timeout 6h




