name: Tests

on:
  pull_request:
    branches:
      - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          docker-compose-version: 'v2'

      - name: Run unit tests
        run: ./stack compose-unit-tests 

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install golang
        uses: actions/setup-go@v5

      - name: Install node
        uses: actions/setup-node@v4

      - name: Build Docker Images
        run: ./stack compose-build

      - name: Initialize chain
        run: ./stack compose-init

      - name: Run stack
        run: ./stack compose-up -d

      - name: Run tests
        run: ./stack integration-tests
