name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./hardhat

      - name: Run unit tests
        run: ./stack unit-tests

      - name: Run hardhat unit tests
        run: ./stack unit-tests-hardhat

  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install golang
        uses: actions/setup-go@v5

      - name: Install node
        uses: actions/setup-node@v4

      - name: Build Base Docker Images
        run: ./stack compose-build-services

      - name: Initialize chain
        run: ./stack compose-init

      - name: Start base services
        run: |
          ./stack compose-services -d
          sleep 30

      - name: Start solver
        run: |
          ./stack solver --disable-telemetry=true --api-host="" > solver.log &
          sleep 5

      - name: Run solver integration tests
        run: ./stack integration-tests-solver

      - name: Start resource provider
        run: |
          ./stack resource-provider --disable-telemetry=true --api-host="" > resource-provider.log &
          sleep 5

      - name: Run main integration tests
        run: ./stack integration-tests

      - name: Display solver logs
        run: cat solver.log

      - name: Display resource provider logs
        run: cat resource-provider.log

      - name: Display chain logs
        run: docker logs chain
