name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./hardhat

      - name: Run unit tests
        run: ./stack unit-tests
        
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Install golang
        uses: actions/setup-go@v5

      - name: Install node
        uses: actions/setup-node@v4

      - name: Build Docker Images
        run: ./stack compose-build

      - name: Initialize chain
        run: ./stack compose-init

      - name: Run stack
        env:
          DISABLE_TELEMETRY: true
        run: ./stack compose-up -d

      - name: Run tests
        env:
          LOG_LEVEL: debug
        run: ./stack integration-tests

      - name: Display resource provider logs
        run: docker logs resource-provider

      - name: Display solver logs
        run: docker logs solver

      - name: Display chain logs
        run: docker logs chain
